name: Test Tutorials

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[all]  # Install all dependencies, including dev

      - name: Test tutorials notebooks
        run: pytest --nbmake tutorials/notebooks --nbmake-timeout=600